# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'webview.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1012, 671)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.webView = QtWebEngineWidgets.QWebEngineView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webView.sizePolicy().hasHeightForWidth())
        self.webView.setSizePolicy(sizePolicy)
        self.webView.setMinimumSize(QtCore.QSize(0, 300))
        self.webView.setUrl(QtCore.QUrl("about:blank"))
        self.webView.setObjectName("webView")
        self.gridLayout.addWidget(self.webView, 2, 1, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 100))
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 3, 1, 1, 1)
        self.screenshotButton = QtWidgets.QPushButton(self.centralwidget)
        self.screenshotButton.setObjectName("screenshotButton")
        self.gridLayout.addWidget(self.screenshotButton, 1, 1, 1, 1)
        self.displayLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayLabel.sizePolicy().hasHeightForWidth())
        self.displayLabel.setSizePolicy(sizePolicy)
        self.displayLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.displayLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.displayLabel.setObjectName("displayLabel")
        self.gridLayout.addWidget(self.displayLabel, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.loadButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadButton.setObjectName("loadButton")
        self.gridLayout_3.addWidget(self.loadButton, 0, 0, 1, 1)
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout_3.addWidget(self.saveButton, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 2, 3, 1, 1)
        self.contentCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.contentCheck.setObjectName("contentCheck")
        self.gridLayout_2.addWidget(self.contentCheck, 0, 3, 1, 1)
        self.ownedCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.ownedCheck.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ownedCheck.setObjectName("ownedCheck")
        self.gridLayout_2.addWidget(self.ownedCheck, 0, 0, 1, 1)
        self.inactiveCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.inactiveCheck.setObjectName("inactiveCheck")
        self.gridLayout_2.addWidget(self.inactiveCheck, 0, 1, 1, 1)
        self.servicesCombo = QtWidgets.QComboBox(self.centralwidget)
        self.servicesCombo.setObjectName("servicesCombo")
        self.servicesCombo.addItem("")
        self.servicesCombo.addItem("")
        self.servicesCombo.addItem("")
        self.gridLayout_2.addWidget(self.servicesCombo, 1, 0, 1, 1)
        self.marksCombo = QtWidgets.QComboBox(self.centralwidget)
        self.marksCombo.setObjectName("marksCombo")
        self.marksCombo.addItem("")
        self.marksCombo.addItem("")
        self.marksCombo.addItem("")
        self.gridLayout_2.addWidget(self.marksCombo, 1, 1, 1, 1)
        self.priorityCombo = QtWidgets.QComboBox(self.centralwidget)
        self.priorityCombo.setObjectName("priorityCombo")
        self.priorityCombo.addItem("")
        self.priorityCombo.addItem("")
        self.priorityCombo.addItem("")
        self.gridLayout_2.addWidget(self.priorityCombo, 2, 0, 1, 1)
        self.domainCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.domainCheck.setObjectName("domainCheck")
        self.gridLayout_2.addWidget(self.domainCheck, 0, 2, 1, 1)
        self.jurisdictionCombo = QtWidgets.QComboBox(self.centralwidget)
        self.jurisdictionCombo.setObjectName("jurisdictionCombo")
        self.jurisdictionCombo.addItem("")
        self.jurisdictionCombo.addItem("")
        self.jurisdictionCombo.addItem("")
        self.jurisdictionCombo.addItem("")
        self.gridLayout_2.addWidget(self.jurisdictionCombo, 2, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.letterButton = QtWidgets.QPushButton(self.centralwidget)
        self.letterButton.setObjectName("letterButton")
        self.horizontalLayout.addWidget(self.letterButton)
        self.udrpButton = QtWidgets.QPushButton(self.centralwidget)
        self.udrpButton.setObjectName("udrpButton")
        self.horizontalLayout.addWidget(self.udrpButton)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 3, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.watchButton = QtWidgets.QPushButton(self.centralwidget)
        self.watchButton.setObjectName("watchButton")
        self.horizontalLayout_2.addWidget(self.watchButton)
        self.emailButton = QtWidgets.QPushButton(self.centralwidget)
        self.emailButton.setObjectName("emailButton")
        self.horizontalLayout_2.addWidget(self.emailButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 2, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.newButton = QtWidgets.QPushButton(self.centralwidget)
        self.newButton.setObjectName("newButton")
        self.horizontalLayout_4.addWidget(self.newButton)
        self.openButton = QtWidgets.QPushButton(self.centralwidget)
        self.openButton.setObjectName("openButton")
        self.horizontalLayout_4.addWidget(self.openButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 2, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1012, 28))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuAction = QtWidgets.QMenu(self.menubar)
        self.menuAction.setObjectName("menuAction")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_Domain = QtWidgets.QAction(MainWindow)
        self.actionNew_Domain.setObjectName("actionNew_Domain")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionUser_Guide = QtWidgets.QAction(MainWindow)
        self.actionUser_Guide.setObjectName("actionUser_Guide")
        self.actionCredts = QtWidgets.QAction(MainWindow)
        self.actionCredts.setObjectName("actionCredts")
        self.actionLicense = QtWidgets.QAction(MainWindow)
        self.actionLicense.setObjectName("actionLicense")
        self.actionLetter = QtWidgets.QAction(MainWindow)
        self.actionLetter.setObjectName("actionLetter")
        self.actionEmail = QtWidgets.QAction(MainWindow)
        self.actionEmail.setObjectName("actionEmail")
        self.actionUDRP = QtWidgets.QAction(MainWindow)
        self.actionUDRP.setObjectName("actionUDRP")
        self.actionOpen_case = QtWidgets.QAction(MainWindow)
        self.actionOpen_case.setObjectName("actionOpen_case")
        self.actionLoad_data = QtWidgets.QAction(MainWindow)
        self.actionLoad_data.setObjectName("actionLoad_data")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionWatch = QtWidgets.QAction(MainWindow)
        self.actionWatch.setObjectName("actionWatch")
        self.menuFile.addAction(self.actionNew_Domain)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionOpen_case)
        self.menuFile.addAction(self.actionLoad_data)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionUser_Guide)
        self.menuHelp.addAction(self.actionCredts)
        self.menuHelp.addAction(self.actionLicense)
        self.menuAction.addAction(self.actionLetter)
        self.menuAction.addAction(self.actionEmail)
        self.menuAction.addAction(self.actionUDRP)
        self.menuAction.addAction(self.actionWatch)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAction.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.screenshotButton, self.textBrowser)
        MainWindow.setTabOrder(self.textBrowser, self.ownedCheck)
        MainWindow.setTabOrder(self.ownedCheck, self.inactiveCheck)
        MainWindow.setTabOrder(self.inactiveCheck, self.domainCheck)
        MainWindow.setTabOrder(self.domainCheck, self.contentCheck)
        MainWindow.setTabOrder(self.contentCheck, self.servicesCombo)
        MainWindow.setTabOrder(self.servicesCombo, self.marksCombo)
        MainWindow.setTabOrder(self.marksCombo, self.priorityCombo)
        MainWindow.setTabOrder(self.priorityCombo, self.jurisdictionCombo)
        MainWindow.setTabOrder(self.jurisdictionCombo, self.watchButton)
        MainWindow.setTabOrder(self.watchButton, self.emailButton)
        MainWindow.setTabOrder(self.emailButton, self.letterButton)
        MainWindow.setTabOrder(self.letterButton, self.udrpButton)
        MainWindow.setTabOrder(self.udrpButton, self.newButton)
        MainWindow.setTabOrder(self.newButton, self.openButton)
        MainWindow.setTabOrder(self.openButton, self.loadButton)
        MainWindow.setTabOrder(self.loadButton, self.saveButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.screenshotButton.setText(_translate("MainWindow", "Screenshot"))
        self.displayLabel.setText(_translate("MainWindow", "No data loaded"))
        self.loadButton.setText(_translate("MainWindow", "Load"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.contentCheck.setText(_translate("MainWindow", "Infringing content"))
        self.ownedCheck.setText(_translate("MainWindow", "Owned"))
        self.inactiveCheck.setText(_translate("MainWindow", "Inactive"))
        self.servicesCombo.setCurrentText(_translate("MainWindow", "Services"))
        self.servicesCombo.setItemText(0, _translate("MainWindow", "Services"))
        self.servicesCombo.setItemText(1, _translate("MainWindow", "Similar services"))
        self.servicesCombo.setItemText(2, _translate("MainWindow", "Identical services"))
        self.marksCombo.setCurrentText(_translate("MainWindow", "Marks"))
        self.marksCombo.setItemText(0, _translate("MainWindow", "Marks"))
        self.marksCombo.setItemText(1, _translate("MainWindow", "Similar marks"))
        self.marksCombo.setItemText(2, _translate("MainWindow", "Identical marks"))
        self.priorityCombo.setCurrentText(_translate("MainWindow", "Priority"))
        self.priorityCombo.setItemText(0, _translate("MainWindow", "Priority"))
        self.priorityCombo.setItemText(1, _translate("MainWindow", "Low priority"))
        self.priorityCombo.setItemText(2, _translate("MainWindow", "High priority"))
        self.domainCheck.setText(_translate("MainWindow", "Infringing domain"))
        self.jurisdictionCombo.setCurrentText(_translate("MainWindow", "Jurisdiction"))
        self.jurisdictionCombo.setItemText(0, _translate("MainWindow", "Jurisdiction"))
        self.jurisdictionCombo.setItemText(1, _translate("MainWindow", "EU"))
        self.jurisdictionCombo.setItemText(2, _translate("MainWindow", "USA"))
        self.jurisdictionCombo.setItemText(3, _translate("MainWindow", "Other"))
        self.letterButton.setText(_translate("MainWindow", "Letter"))
        self.udrpButton.setText(_translate("MainWindow", "UDRP"))
        self.watchButton.setText(_translate("MainWindow", "Watchlist"))
        self.emailButton.setText(_translate("MainWindow", "Email"))
        self.newButton.setText(_translate("MainWindow", "New"))
        self.openButton.setText(_translate("MainWindow", "Open"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuAction.setTitle(_translate("MainWindow", "Actio&n"))
        self.actionNew_Domain.setText(_translate("MainWindow", "&New Domain"))
        self.actionQuit.setText(_translate("MainWindow", "&Quit"))
        self.actionUser_Guide.setText(_translate("MainWindow", "&User Guide"))
        self.actionCredts.setText(_translate("MainWindow", "&Credits"))
        self.actionLicense.setText(_translate("MainWindow", "&License"))
        self.actionLetter.setText(_translate("MainWindow", "&Letter"))
        self.actionEmail.setText(_translate("MainWindow", "&Email"))
        self.actionUDRP.setText(_translate("MainWindow", "&UDRP"))
        self.actionOpen_case.setText(_translate("MainWindow", "&Open Case"))
        self.actionLoad_data.setText(_translate("MainWindow", "&Load data"))
        self.actionSave.setText(_translate("MainWindow", "&Save"))
        self.actionWatch.setText(_translate("MainWindow", "Watch"))

from PyQt5 import QtWebEngineWidgets
